export const BRAND = {
  name: "Vantrex Capital",
  shortName: "VANTREX",
  wordmarkSuffix: "CAPITAL",
  legalEntity: "Vantrex Capital LLC",
  tagline: "Professional Brokerage & Wealth Management",
  domain: "vantrexcapital.com",
  url: "https://vantrexcapital.com",
  supportEmail: "support@vantrexcapital.com",
  complianceEmail: "compliance@vantrexcapital.com",
  registrationNumber: "VTX-2021-001",
  foundedYear: 2021,
  twitter: "@VantrexCapital",
  colors: {
    navy: "#09090B",
    slate: "#161616",
    gold: "#C9A227",
    emerald: "#10B981",
    emeraldSoft: "#34D399",
    emeraldGlow: "#059669",
    offWhite: "#FAFAFA",
  },
} as const;
