export const BRAND = {
  name: "Vantrex Capital",
  shortName: "VANTREX",
  wordmarkSuffix: "CAPITAL",
  legalEntity: "Vantrex Capital LLC",
  tagline: "Institutional-grade trading. Built for everyone.",
  domain: "vantrexcapital.com",
  url: "https://vantrexcapital.com",
  supportEmail: "support@vantrexcapital.com",
  complianceEmail: "compliance@vantrexcapital.com",
  registrationNumber: "VTX-2021-001",
  foundedYear: 2021,
  twitter: "@VantrexCapital",
  /** ONYX-matching lime + charcoal system */
  colors: {
    navy: "#0F0F0F",
    slate: "#1A1A1A",
    gold: "#FBBF24",
    emerald: "#E2FF4C",
    emeraldSoft: "#F0FFD6",
    emeraldGlow: "#CCE835",
    offWhite: "#F4F7F6",
    charcoal: "#111111",
    lime: "#E2FF4C",
  },
} as const;
